<#
.SYNOPSIS
  READ-ONLY discovery of AWS resources that may belong to this lab, BEFORE
  Terraform creates anything. Produces docs/existing-resources.md with the
  RESOURCE / CURRENT AWS ID / MANAGED BY TERRAFORM? / ACTION table.

.DESCRIPTION
  Looks for: resources tagged Project=<project>, and anything named with the
  mtm prefix (VPCs, RDS, ECS, ECR, Secrets, IAM roles, S3 state bucket), plus
  the GitHub OIDC provider. Only Describe/List/Get calls are made.
  "Managed by Terraform?" is checked against `terraform state list` when a
  state exists.

.EXAMPLE
  ./scripts/discover-aws.ps1 -Region us-east-1
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Region,
    [string]$Project = 'monolith-to-microservices-lab',
    [string]$Prefix = 'mtm',
    [string]$Environment = 'dev'
)

. "$PSScriptRoot/_common.ps1"
if (-not (Test-Command 'aws')) { throw 'AWS CLI required (winget install Amazon.AWSCLI).' }

Write-Step 'AWS identity'
$id = Show-AwsIdentity

function Invoke-AwsJson([string[]]$CliArgs) {
    $out = & aws @CliArgs --region $Region --output json 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $out) { return $null }
    return ($out -join "`n") | ConvertFrom-Json
}

$found = New-Object System.Collections.Generic.List[object]
function Add-Found([string]$Type, [string]$Id, [string]$Why) {
    $found.Add([pscustomobject]@{ Type = $Type; Id = $Id; Why = $Why })
}

Write-Step "Tagged resources (Project=$Project)"
$tagged = Invoke-AwsJson @('resourcegroupstaggingapi', 'get-resources', '--tag-filters', "Key=Project,Values=$Project")
if ($tagged) { foreach ($r in $tagged.ResourceTagMappingList) { Add-Found 'tagged' $r.ResourceARN "Project=$Project" } }

Write-Step 'Name-prefix scan'
$vpcs = Invoke-AwsJson @('ec2', 'describe-vpcs', '--filters', "Name=tag:Name,Values=$Prefix-*")
if ($vpcs) { foreach ($v in $vpcs.Vpcs) { Add-Found 'aws_vpc' $v.VpcId 'Name tag prefix' } }

$rds = Invoke-AwsJson @('rds', 'describe-db-instances')
if ($rds) { foreach ($d in $rds.DBInstances | Where-Object { $_.DBInstanceIdentifier -like "$Prefix-*" }) { Add-Found 'aws_db_instance' $d.DBInstanceIdentifier 'identifier prefix' } }

$clusters = Invoke-AwsJson @('ecs', 'list-clusters')
if ($clusters) { foreach ($c in $clusters.clusterArns | Where-Object { $_ -like "*:cluster/$Prefix-*" }) { Add-Found 'aws_ecs_cluster' $c 'name prefix' } }

$ecr = Invoke-AwsJson @('ecr', 'describe-repositories')
if ($ecr) { foreach ($r in $ecr.repositories | Where-Object { $_.repositoryName -like "$Prefix/*" }) { Add-Found 'aws_ecr_repository' $r.repositoryName 'name prefix' } }

$secrets = Invoke-AwsJson @('secretsmanager', 'list-secrets', '--filters', "Key=name,Values=$Prefix/")
if ($secrets) { foreach ($s in $secrets.SecretList) { Add-Found 'aws_secretsmanager_secret' $s.Name 'name prefix' } }

$lbs = Invoke-AwsJson @('elbv2', 'describe-load-balancers')
if ($lbs) { foreach ($l in $lbs.LoadBalancers | Where-Object { $_.LoadBalancerName -like "$Prefix-*" }) { Add-Found 'aws_lb' $l.LoadBalancerName 'name prefix' } }

# Global services
$roles = Invoke-AwsJson @('iam', 'list-roles')
if ($roles) { foreach ($r in $roles.Roles | Where-Object { $_.RoleName -like "$Prefix-*" }) { Add-Found 'aws_iam_role' $r.RoleName 'name prefix' } }

$oidc = Invoke-AwsJson @('iam', 'list-open-id-connect-providers')
if ($oidc) { foreach ($p in $oidc.OpenIDConnectProviderList | Where-Object { $_.Arn -like '*token.actions.githubusercontent.com' }) { Add-Found 'aws_iam_openid_connect_provider' $p.Arn 'GitHub OIDC (one per account)' } }

$buckets = Invoke-AwsJson @('s3api', 'list-buckets')
if ($buckets) { foreach ($b in $buckets.Buckets | Where-Object { $_.Name -like "$Prefix-tfstate-*" }) { Add-Found 'aws_s3_bucket' $b.Name 'state bucket name' } }

# Managed by Terraform? (only if a remote state is reachable)
$stateText = ''
$envDir = Get-EnvDir $Environment
if ((Test-Path (Join-Path $envDir 'backend.hcl')) -and (Test-Path (Join-Path $envDir '.terraform'))) {
    try { $stateText = Get-TerraformOutput -WorkDir $envDir -Arguments @('state', 'pull') } catch { $stateText = '' }
}
$bootstrapState = Join-Path $script:RepoRoot 'bootstrap/terraform.tfstate'
if (Test-Path $bootstrapState) { $stateText += (Get-Content $bootstrapState -Raw) }

$rows = foreach ($f in ($found | Sort-Object Type, Id -Unique)) {
    $leaf = ($f.Id -split '[:/]')[-1]
    $managed = if ($stateText -and $stateText.Contains($leaf)) { 'yes' } else { 'no' }
    $action = if ($managed -eq 'yes') { 'KEEP (already managed)' } else { 'REVIEW: IMPORT / KEEP UNMANAGED / CREATE NEW / IGNORE' }
    "| $($f.Type) | ``$($f.Id)`` | $managed | $action |"
}

$report = Join-Path $script:RepoRoot 'docs/existing-resources.md'
$lines = @(
    '# Existing AWS resources (discovery)',
    '',
    "Generated by ``scripts/discover-aws.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm') for account ``$($id.Account)``, region ``$Region``.",
    '',
    '| RESOURCE | CURRENT AWS ID | MANAGED BY TERRAFORM? | ACTION |',
    '|---|---|---|---|'
)
if ($rows) { $lines += $rows } else { $lines += '| (none found) | - | - | CREATE NEW |' }
$lines += @('', 'Decide each ACTION before the first apply. Import procedure: docs/import-strategy.md')
Set-Content -Path $report -Value $lines -Encoding utf8

Write-Host ''
Write-Host ("{0} candidate resource(s). Report: docs/existing-resources.md" -f @($found).Count)
