# Partial backend configuration: bucket and region are account-specific and
# come from backend.hcl (git-ignored, generated by scripts/bootstrap.ps1) or
# from -backend-config flags in CI.
#
#   terraform init -backend-config=backend.hcl
#
# use_lockfile = S3 native locking (a <key>.tflock object, conditional writes).
# No DynamoDB table: DynamoDB-based locking is deprecated.
terraform {
  backend "s3" {
    key          = "dev/terraform.tfstate"
    encrypt      = true
    use_lockfile = true
  }
}
